### ISSUE TITLE
Compile in Xcode Beta?

### ISSUE THREAD

**Issue by DutchDude69** [4np/UitzendingGemist#9] opened 2016-09-02 05:53 UTC
Hi,

Quick question.
Does your project already build correctly in xcode 8 beta?

Kind regards,
DD

**Comment by 4np** [comment] 2016-09-07 12:41
It might if you do not convert to the new Swift syntax, but I still need to convert the code. For now I would advise to hold off upgrading to the new tvOS when it launches (today?) until I have checked and updated the code to the new Swift syntax and tested out the new tvOS version. If you're feeling adventurous, give it a go ;)

**Comment by erwindebeus** [comment] 2016-09-15 21:35
It almost works in Xcode 8 after updating the pods and setting the build option 'Use Legacy Swift Language Version" to yes. There still is an issue with RealSwift, but the developers have already announced a fix. [https://github.com/realm/realm-cocoa/issues/3894](https://github.com/realm/realm-cocoa/issues/3894). With a bit of luck, it will compile this weekend.

**Comment by 4np** [comment] 2016-09-17 15:28
Working on updating the project to [Swift 3 / tvOS 10 / Xcode 8](https://github.com/4np/UitzendingGemist/tree/swift3) but unfortunately it's more work than anticipated (in addition to the drastic language changes all the views are messed up in Xcode 8)... Hopefully I will get this worked out soon.

**Comment by 4np** [comment] 2016-09-18 09:37
Apparently I am [not the only one](https://forums.developer.apple.com/thread/62313)... ~~Filed radar 28354863 with Apple~~ (closed)...

![issues](https://www.dropbox.com/s/nrl1njwb0jpymer/InterfaceBuilder%20Issues.png?dl=1)

**Comment by 4np** [comment] 2016-09-21 15:42
I found the cause of the issue...  Apparently Xcode 8's Autolayout is respecting the constraints differently than it did in Xcode 7. There seems to be an additional issue where collection view cells seem to default to 1000x1000 after resizing to the Interface Builder's configure size (for example 375x211). As I was generating images and caching images based on an image's frame, this led to stretched images on screen. Hardcoding the image sizes is for now a workaround, hopefully that will be something that gets fixed by Apple in a future release...

**Comment by 4np** [comment] 2016-09-21 19:41
Fixed in [version 1.0.0](https://github.com/4np/UitzendingGemist/releases/tag/1.0.0)  🙌🏻 _(Xcode 8, tvOS 10 and Swift 3)_.

**Closed as completed by 4np** 2016-09-21 19:41 UTC
