### ISSUE TITLE
Time out when trying to watch episodes from Australia

### ISSUE THREAD

**Issue by TookiTheGreat** [4np/UitzendingGemist#18] opened 2017-02-05 03:56 UTC
Since updating to tvOS 10.1.1 we can't watch anything anymore. It looks like we get a timeout on every episode we are trying to watch.

**Comment by 4np** [comment] 2017-02-07 08:56
I'm sorry to hear you are experiencing timeouts. I am also on 10.1.1 and we use the app almost daily but it's all working fine for me, no issues here. To rule out that things changed on the end of the Dutch public broadcaster: does watching videos directly from [the website](http://www.npo.nl/live) work for you?

Are you sure you are not experiencing #16 ?

**Comment by TookiTheGreat** [comment] 2017-02-07 10:06
We have reverted to watching the iPad and AirPlay. That still works, though seems to take more time to get started (we are in a rural area with slow Internet so the initial wait can run into close to a minute) and can get quite pixellated. But it works. I will try the delete and reinstall trick next. I assumed that recompiling and overwriting the app would also clear the cache, but maybe I was wrong about that.

**Comment by 4np** [comment] 2017-02-07 11:40
Realm does clean up its transaction log on launch, but if #16 occurs it cannot clean up anymore. I have not experienced the issue anymore since [1.2.0](https://github.com/4np/UitzendingGemist/releases/tag/1.2.0) but you never know. I suspect this is not happening to you as you are able to use the app. 

It sounds like the delay might be caused by the latency in the internet connection, did you see any other video playing apps on Apple TV fail playing back since tvOS 10.1.1? The app is using the built in video player, perhaps Apple changed something in 10.1.1. Unfortunately I do not have any control on how they handle timeouts in the video player, perhaps they changed something in the video player's implementation? I can't seem to find any -recent- issues regarding AVPlayer timeouts on Apple's developer forums...

**Comment by TookiTheGreat** [comment] 2017-02-07 13:30
All other video playing apps work fine: Netflix, iTunes, Stan, TED, ... What I see in the uitzendinggemist app is the wait-cursor (the rotating stripes) then a brief flash of black screen with a tiny symbol, like a stop-sign in the left-hand corner, then it goes back to the wait cursor. I will try deinstalling and reinstalling to see if I can get it to work, but I do not feel too hopeful. Is there any way to debug this to get more information on where exactly things fail?

**Comment by 4np** [comment] 2017-02-07 13:41
When you deploy Uitzending Gemist to your Apple TV and leave the Apple TV connected to your Mac with Xcode open, you should see debug output in the debug panel. Do you see any errors when trying to play back videos?

![pasted_image_07_02_17_14_39](https://cloud.githubusercontent.com/assets/1049693/22693421/815b3552-ed43-11e6-8209-3b532ff539c8.jpg)

You can also try running in the simulator without deploying onto your Apple TV and inspecting the debug panel for errors:

![pasted_image_07_02_17_14_43](https://cloud.githubusercontent.com/assets/1049693/22693517/e9d2f4b2-ed43-11e6-94e8-a2f95307384d.jpg)

Some questions: does this happen for watching episodes as well as live tv / themed channels? Do the YouTube video's play (for example those for the '_Zondag met Lubach_' program)?

**Comment by TookiTheGreat** [comment] 2017-02-07 13:43
I will have a look tomorrow - or later in the week depending on available time. It's way past my bedtime here in Australia now ;-).

**Comment by 4np** [comment] 2017-02-07 13:45
Haha, that happens to me too often as well ;) Have a good night!

**Comment by TookiTheGreat** [comment] 2017-02-08 02:38
I'm beginning to suspect it could be a firewall issue. I am using Cujo (www.getcujo.com) to monitor my network for potential threats and block access to suspected sites. Looking at the Cujo log files it seems the AppleTV is accessing some suspected sites when retrieving episodes from the uitzendinggemist website. This could mean their site has been reported as housing malware or viruses. I will take the AppleTV out of Cujo's reach to see if that makes any difference. Don't know yet when I get around to this: family will arrive soon, expecting to be entertained for the coming 7 days ;-).

**Comment by TookiTheGreat** [comment] 2017-02-08 07:43
Yup. Definitely firewall related. Not quite sure what is causing the problem exactly, but when I turn the firewall off everything works as expected. I wonder what changed: is tvOS 10.1.1 the cause, or was that just a freaky coincidence? I don't like turning off the firewall but for the sake of watching Uitzending Gemist I will risk being hacked by Russian/American/Jihadist/Alien (pick whatever scares you most) nerds hoping to use information about my viewing patterns to blackmail me in the future.

**Comment by 4np** [comment] 2017-02-08 07:44
Ah, that might indeed be possible. The URL patterns you can expect the app to call are:

- apps-api.uitzendinggemist.nl (the API)
- api.github.com (check for new releases)
- *.omroep.nl (images, videos and live streams)
- googleapis.com (youtube API)
- youtube.com (youtube videos)

So if you exclude these from the firewall rules for your Apple TV it _should_ work.

But it's indeed strange this popped up after the TV OS 10.1.1 update? I would be curious to know what triggered this :)

**Comment by TookiTheGreat** [comment] 2017-02-08 07:46
Thanks. That might help finding the offending IP address(es).

**Comment by 4np** [comment] 2017-02-08 07:47
I will add those to the readme as others might stumble on this issue as well... I'm glad you found the cause ;) One side note is that the URLs for the video and image content for both the NPO as well as YouTube come from the APIs, so while unlikely, they _might_ change in the future. Keep in mind that videos stop working or images stop loading that perhaps the content is coming from different URLs.

**Comment by 4np** [comment] 2017-03-02 18:42
I assume this issue is solved, so I'll close it for now...

**Closed as completed by 4np** 2017-03-02 18:42 UTC
Labels: help wanted
